
CREATE DATABASE BD_SISGECU_TEST;
USE BD_SISGECU_TEST;

-- Tabla ADMINISTRADOR
CREATE TABLE ADMINISTRADOR (
  ID_ADMINISTRADOR INT (11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CEDULA VARCHAR(20) NOT NULL UNIQUE,
  NOMBRES VARCHAR(64) NOT NULL,
  APELLIDOS VARCHAR(64) NOT NULL,
  CORREOINS VARCHAR(100) NOT NULL,
  CONTRASEÑA VARCHAR(100) NOT NULL,
  TELEFONO VARCHAR(20) NOT NULL,
  ROL VARCHAR(20) NOT NULL
);

-- Tabla ESTUDIANTE
CREATE TABLE ESTUDIANTE (
  ID_ESTUDIANTE INT (11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CEDULA VARCHAR(20) NOT NULL UNIQUE,
  NOMBRES VARCHAR(64) NOT NULL,
  APELLIDOS VARCHAR(64) NOT NULL,
  GENERO VARCHAR(10) NOT NULL,
  CORREOINS VARCHAR(100) NOT NULL,
  CONTRASEÑA VARCHAR(100) NOT NULL ,
  PROGRAMA VARCHAR(64) NOT NULL,
  CUATRIMESTRE INT (2) NOT NULL,
  ESTADO VARCHAR(20) NOT NULL,
  FECHARE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ROL VARCHAR(20) NOT NULL
);

-- Tabla REPARTIDOR
CREATE TABLE REPARTIDOR (
  ID_REPARTIDOR INT (11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CEDULA VARCHAR(20) NOT NULL UNIQUE,
  NOMBRES VARCHAR(64) NOT NULL,
  APELLIDOS VARCHAR(64) NOT NULL,
  CORREOINS VARCHAR(100) NOT NULL,
  CONTRASEÑA VARCHAR(100) NOT NULL,
  TELEFONO VARCHAR(20) NOT NULL,
  ROL VARCHAR(20) NOT NULL,
  GENERO VARCHAR(10) NOT NULL,
  FECHAING TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHASAL DATE,
  ESTADO VARCHAR(20) NOT NULL,
  TURNO VARCHAR(20) NOT NULL
);

-- Tabla SEDE
CREATE TABLE SEDE (
  ID_SEDE INT (2) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(64) NOT NULL ,
  DIRECCION VARCHAR(100) NOT NULL
);

-- Tabla CATEGORIA
CREATE TABLE CATEGORIA (
  ID_CATEGORIA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(64) NOT NULL,
  DESCRIPCION TEXT NOT NULL
);

-- Tabla ALIMENTO
CREATE TABLE ALIMENTO (
  ID_ALIMENTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  ID_CATEGORIA INT NOT NULL,
  NOMBRE VARCHAR(64) NOT NULL,
  CANTIDAD INT NOT NULL,
  FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

-- Tabla CUPON
CREATE TABLE CUPON (
  ID_CUPON INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  ID_ALIMENTO INT NOT NULL,
  CODIGO_QR VARCHAR(255),
  FECHACREA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHAEXP DATE,
  ESTADO VARCHAR(20) NOT NULL,
  ID_ESTUDIANTE INT NOT NULL,
  FOREIGN KEY (ID_ALIMENTO) REFERENCES ALIMENTO(ID_ALIMENTO),
  FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE)
);

-- Tabla ENTREGA
CREATE TABLE ENTREGA (
  ID_ENTREGA INT PRIMARY KEY AUTO_INCREMENT,
  ID_REPARTIDOR INT NOT NULL,
  ID_ESTUDIANTE INT NOT NULL,
  ID_SEDE INT NOT NULL,
  ID_CUPON INT NOT NULL,
  FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_REPARTIDOR) REFERENCES REPARTIDOR(ID_REPARTIDOR),
  FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
  FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID_SEDE),
  FOREIGN KEY (ID_CUPON) REFERENCES CUPON(ID_CUPON)
);

-- Índices para optimización
CREATE INDEX idx_cupon_alimento ON CUPON (ID_ALIMENTO);
CREATE INDEX idx_cupon_estudiante ON CUPON (ID_ESTUDIANTE);
CREATE INDEX idx_alimento_categoria ON ALIMENTO (ID_CATEGORIA);
CREATE INDEX idx_entrega_estudiante ON ENTREGA (ID_ESTUDIANTE);
CREATE INDEX idx_entrega_repartidor ON ENTREGA (ID_REPARTIDOR);
CREATE INDEX idx_entrega_sede ON ENTREGA (ID_SEDE);
CREATE INDEX idx_entrega_cupon ON ENTREGA (ID_CUPON);
